### ISSUE TITLE
Step by step tutorial required

### ISSUE THREAD

**Issue by kaustubhcs** [TheNetAdmin/MightyPC#1]
Although I do understand this was a side project, step-by-step guidelines/documentation of this project would be extremely useful.

This is a very useful tool that would benefit from documentation (Even if not exhaustive).
Are there any plans to create documentation for this tool?

**Comment by TheNetAdmin** [comment]
I did plan to write a tutorial/doc, but currently I'm on an internship and do not have much time until I'm back to school this fall.

If you're interested in using this tool, what we can do (and actually what we did for the past few conferebces) is to meet with you online and introduce the general workflow, then answer questions through emails. If this helps with your usage, please first contact Aamer and Jishen (they served as program chairs at the time this tool is developed), and then we can set up some online meetings.

**Comment by kaustubhcs** [comment]
That would be great! Can we coordinate over email? Could you send me the email IDs of Aamer and Jishen?
